CC = gcc

CFLAGS = -std=c99 -g
LDFLAGS =  
ODIR = bin
PROG = a.out

all: main.o log.o
	$(CC) $(LDFLAGS) $(ODIR)/*.o -o $(ODIR)/$(PROG)

main.o: main.c
	$(CC) $(CFLAGS) -c main.c -o $(ODIR)/main.o

log.o: log.c
	$(CC) $(CFLAGS) -c log.c -o $(ODIR)/log.o

clean:
	rm -f $(ODIR)/$(PROG) $(ODIR)/*.o
